version: '3.4'

services:
  duftfinder.web:
    #image: flozi76/duftfinder.web
    build:
      context: ./Duftfinder.Core
    environment:
      - MongoDatabaseName=duftfinder
      - MongoConnectionString=mongodb+srv://administrator:AHOZ5pn18Gari4IZ@duftfinder-vdzwu.mongodb.net/test?retryWrites=true
    ports: 
      - "8080:80"