//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duftfinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duftfinder.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für die Bestätigung Ihrer Registration.
        /// </summary>
        public static string Account_AccountVerified {
            get {
                return ResourceManager.GetString("Account_AccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ätherische Öle..
        /// </summary>
        public static string Account_AccountVerified_SearchEssentialOil {
            get {
                return ResourceManager.GetString("Account_AccountVerified_SearchEssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis es so weit ist, informieren  Sie sich über.
        /// </summary>
        public static string Account_AccountVerified_SearchEssentialOilText {
            get {
                return ResourceManager.GetString("Account_AccountVerified_SearchEssentialOilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Registration ist hiermit bestätigt. Ihr Account muss nun von der Administratorin freigeschalten werden. Dies kann einige Tage dauern. Sobald Ihr Account zur Nutzung bereit ist, werden Sie per E-Mail informiert..
        /// </summary>
        public static string Account_AccountVerifiedText {
            get {
                return ResourceManager.GetString("Account_AccountVerifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde geändert.
        /// </summary>
        public static string Account_ChangeOrResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account_ChangeOrResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können sich nun mit Ihrem neuen Passwort.
        /// </summary>
        public static string Account_ChangeOrResetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account_ChangeOrResetPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  einloggen..
        /// </summary>
        public static string Account_ChangeOrResetPasswordConfirmationTextLogin {
            get {
                return ResourceManager.GetString("Account_ChangeOrResetPasswordConfirmationTextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oder wollen Sie es.
        /// </summary>
        public static string Account_ChangePasswordText {
            get {
                return ResourceManager.GetString("Account_ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ändern?.
        /// </summary>
        public static string Account_ChangePasswordTextChange {
            get {
                return ResourceManager.GetString("Account_ChangePasswordTextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string Account_FirstName {
            get {
                return ResourceManager.GetString("Account_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        public static string Account_ForgotPassword {
            get {
                return ResourceManager.GetString("Account_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie erhalten nun eine automatische E-Mail an Ihre angegebene E-Mail-Adresse. Um das Passwort zu ändern, klicken Sie bitte den in der E-Mail enthaltene Link..
        /// </summary>
        public static string Account_ForgotPasswordConfirmationText {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie Ihr Passwort.
        /// </summary>
        public static string Account_ForgotPasswordText {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  vergessen .
        /// </summary>
        public static string Account_ForgotPasswordTextForgot {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordTextForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string Account_LastName {
            get {
                return ResourceManager.GetString("Account_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        public static string Account_NewPassword {
            get {
                return ResourceManager.GetString("Account_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altes Passwort.
        /// </summary>
        public static string Account_OldPassword {
            get {
                return ResourceManager.GetString("Account_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        public static string Account_PasswordConfirmation {
            get {
                return ResourceManager.GetString("Account_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keinen Account? Registrieren Sie sich.
        /// </summary>
        public static string Account_RegisterNowText {
            get {
                return ResourceManager.GetString("Account_RegisterNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  jetzt..
        /// </summary>
        public static string Account_RegisterNowTextNow {
            get {
                return ResourceManager.GetString("Account_RegisterNowTextNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren Sie sich bei Duftfinder, um weitere Funktionen zu nutzen. Nach der Registration muss Ihr Account von der Administratorin bestätigt werden. Dies kann einige Tage dauern. Ihr Account wird erst dann nutzbar sein..
        /// </summary>
        public static string Account_RegisterText {
            get {
                return ResourceManager.GetString("Account_RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vielen Dank für Ihre Registrierung.
        /// </summary>
        public static string Account_RegistrationConfirmation {
            get {
                return ResourceManager.GetString("Account_RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ätherische Öle..
        /// </summary>
        public static string Account_RegistrationConfirmation_SearchEssentialOil {
            get {
                return ResourceManager.GetString("Account_RegistrationConfirmation_SearchEssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis es so weit ist, informieren  Sie sich über.
        /// </summary>
        public static string Account_RegistrationConfirmation_SearchEssentialOilText {
            get {
                return ResourceManager.GetString("Account_RegistrationConfirmation_SearchEssentialOilText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie erhalten nun eine automatische Bestätigungs-E-Mail an Ihre angegebene E-Mail-Adresse. Um die Registration zu bestätigen, klicken Sie bitte den in der E-Mail enthaltene Link. Erst dann wird die Administratorin über Ihrer Registration informiert..
        /// </summary>
        public static string Account_RegistrationConfirmationText {
            get {
                return ResourceManager.GetString("Account_RegistrationConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melden Sie sich bei Duftfinder an, um weitere Funktionen zu nutzen..
        /// </summary>
        public static string Account_SignInText {
            get {
                return ResourceManager.GetString("Account_SignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string Action_Browse {
            get {
                return ResourceManager.GetString("Action_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string Action_ChangePassword {
            get {
                return ResourceManager.GetString("Action_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Action_Details {
            get {
                return ResourceManager.GetString("Action_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort beantragen.
        /// </summary>
        public static string Action_ForgotPassword {
            get {
                return ResourceManager.GetString("Action_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Action_Ok {
            get {
                return ResourceManager.GetString("Action_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche zurücksetzen.
        /// </summary>
        public static string Action_ResetSearch {
            get {
                return ResourceManager.GetString("Action_ResetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugang zu innerer Stärke.
        /// </summary>
        public static string CategoryValue_AccessToInnerStrength {
            get {
                return ResourceManager.GetString("CategoryValue_AccessToInnerStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziele erreichen: Aktivierungsniveau.
        /// </summary>
        public static string CategoryValue_AchievingGoalsActivationLevel {
            get {
                return ResourceManager.GetString("CategoryValue_AchievingGoalsActivationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziele erreichen: Aufmerksamkeit.
        /// </summary>
        public static string CategoryValue_AchievingGoalsAttention {
            get {
                return ResourceManager.GetString("CategoryValue_AchievingGoalsAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziele erreichen: Nerven.
        /// </summary>
        public static string CategoryValue_AchievingGoalsNerves {
            get {
                return ResourceManager.GetString("CategoryValue_AchievingGoalsNerves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blockaden auflösen.
        /// </summary>
        public static string CategoryValue_BlockageDissolving {
            get {
                return ResourceManager.GetString("CategoryValue_BlockageDissolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blutzirkulation.
        /// </summary>
        public static string CategoryValue_BloodCirculation {
            get {
                return ResourceManager.GetString("CategoryValue_BloodCirculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endokrinum: Hormone.
        /// </summary>
        public static string CategoryValue_EndocrineHormones {
            get {
                return ResourceManager.GetString("CategoryValue_EndocrineHormones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterisches Nervensystem.
        /// </summary>
        public static string CategoryValue_EntericNervousSystem {
            get {
                return ResourceManager.GetString("CategoryValue_EntericNervousSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunsystem.
        /// </summary>
        public static string CategoryValue_ImmuneSystem {
            get {
                return ResourceManager.GetString("CategoryValue_ImmuneSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entzündungen.
        /// </summary>
        public static string CategoryValue_Inflammation {
            get {
                return ResourceManager.GetString("CategoryValue_Inflammation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Jüngere Selbst.
        /// </summary>
        public static string CategoryValue_IntegrationYoungerSelf {
            get {
                return ResourceManager.GetString("CategoryValue_IntegrationYoungerSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meridiane, Angriffe, Yin-Yang.
        /// </summary>
        public static string CategoryValue_MeridiansAttackYinYang {
            get {
                return ResourceManager.GetString("CategoryValue_MeridiansAttackYinYang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muskeln.
        /// </summary>
        public static string CategoryValue_Muscle {
            get {
                return ResourceManager.GetString("CategoryValue_Muscle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nervensystem allgemein.
        /// </summary>
        public static string CategoryValue_NervousSystemGeneral {
            get {
                return ResourceManager.GetString("CategoryValue_NervousSystemGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nervensystem Neurotransmitter.
        /// </summary>
        public static string CategoryValue_NervousSystemNeurotransmitter {
            get {
                return ResourceManager.GetString("CategoryValue_NervousSystemNeurotransmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordnung im Kreis.
        /// </summary>
        public static string CategoryValue_OrderInCircle {
            get {
                return ResourceManager.GetString("CategoryValue_OrderInCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schmerzen.
        /// </summary>
        public static string CategoryValue_Pain {
            get {
                return ResourceManager.GetString("CategoryValue_Pain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haut und Narben.
        /// </summary>
        public static string CategoryValue_SkinAndScars {
            get {
                return ResourceManager.GetString("CategoryValue_SkinAndScars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewebe.
        /// </summary>
        public static string CategoryValue_Tissue {
            get {
                return ResourceManager.GetString("CategoryValue_Tissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        public static string Configuration_Configuration {
            get {
                return ResourceManager.GetString("Configuration_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurationen.
        /// </summary>
        public static string Configuration_Configurations {
            get {
                return ResourceManager.GetString("Configuration_Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Configuration_Description {
            get {
                return ResourceManager.GetString("Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Configuration_Key {
            get {
                return ResourceManager.GetString("Configuration_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Configuration_Value {
            get {
                return ResourceManager.GetString("Configuration_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wirkung wurde bereits ätherischen Ölen zugewiesen..
        /// </summary>
        public static string Confirmation_Delete_EffectAlreadyAssigned {
            get {
                return ResourceManager.GetString("Confirmation_Delete_EffectAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das ätherische Öl wurde bereits Wirkungen zugewiesen..
        /// </summary>
        public static string Confirmation_Delete_EssentialOilAlreadyAssigned {
            get {
                return ResourceManager.GetString("Confirmation_Delete_EssentialOilAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Molekül wurde bereits ätherischen Ölen oder Wirkungen zugewiesen..
        /// </summary>
        public static string Confirmation_Delete_MoleculeAlreadyAssigned {
            get {
                return ResourceManager.GetString("Confirmation_Delete_MoleculeAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie den Eintrag &quot;{0}&quot; wirklich löschen?.
        /// </summary>
        public static string Confirmation_Delete_Text {
            get {
                return ResourceManager.GetString("Confirmation_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen bestätigen.
        /// </summary>
        public static string Confirmation_Delete_Title {
            get {
                return ResourceManager.GetString("Confirmation_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Konfiguration wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeConfigurationValues_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeConfigurationValues_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Wirkungen wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeEffects_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeEffects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die ätherischen Öle wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeEssentialOils_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeEssentialOils_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Moleküle wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeMolecules_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeMolecules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Stoffklassen und Wirkungskategorien wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeSubstancesAndCategories_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeSubstancesAndCategories_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die User wirklich neu initialisieren?.
        /// </summary>
        public static string Confirmation_InitializeUsers_Text {
            get {
                return ResourceManager.GetString("Confirmation_InitializeUsers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl zuweisen.
        /// </summary>
        public static string Effect_AssignEssentialOil {
            get {
                return ResourceManager.GetString("Effect_AssignEssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung:.
        /// </summary>
        public static string Effect_AssignEssentialOil_Effect {
            get {
                return ResourceManager.GetString("Effect_AssignEssentialOil_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molekül zuweisen.
        /// </summary>
        public static string Effect_AssignMolecule {
            get {
                return ResourceManager.GetString("Effect_AssignMolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung:.
        /// </summary>
        public static string Effect_AssignMolecule_Effect {
            get {
                return ResourceManager.GetString("Effect_AssignMolecule_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkungskategorie.
        /// </summary>
        public static string Effect_Category {
            get {
                return ResourceManager.GetString("Effect_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Wirkung erfassen.
        /// </summary>
        public static string Effect_Create {
            get {
                return ResourceManager.GetString("Effect_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Effect_Details {
            get {
                return ResourceManager.GetString("Effect_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung bearbeiten.
        /// </summary>
        public static string Effect_Edit {
            get {
                return ResourceManager.GetString("Effect_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung.
        /// </summary>
        public static string Effect_Effect {
            get {
                return ResourceManager.GetString("Effect_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirksamkeit.
        /// </summary>
        public static string Effect_EffectDegree {
            get {
                return ResourceManager.GetString("Effect_EffectDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkungen.
        /// </summary>
        public static string Effect_Effects {
            get {
                return ResourceManager.GetString("Effect_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Effect_Name {
            get {
                return ResourceManager.GetString("Effect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Account wurde inaktiv gesetzt..
        /// </summary>
        public static string Error_AccountInactive {
            get {
                return ResourceManager.GetString("Error_AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Registration.
        /// </summary>
        public static string Error_AccountVerifiedError {
            get {
                return ResourceManager.GetString("Error_AccountVerifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Tabelle {0} existiert nicht in der Datenbank..
        /// </summary>
        public static string Error_CollectionDoesNotExistInDatabase {
            get {
                return ResourceManager.GetString("Error_CollectionDoesNotExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte kontaktieren Sie die Administratorin..
        /// </summary>
        public static string Error_ContactAdmin {
            get {
                return ResourceManager.GetString("Error_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Account wurde von der Administratorin noch nicht bestätigt. Dies kann einige Tage dauern..
        /// </summary>
        public static string Error_EmailNotYetConfirmed {
            get {
                return ResourceManager.GetString("Error_EmailNotYetConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail oder Passwort ungültig. Bitte versuchen Sie es erneut..
        /// </summary>
        public static string Error_EmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("Error_EmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der eingetragene Wert existiert bereits..
        /// </summary>
        public static string Error_EntityAlreadyExists {
            get {
                return ResourceManager.GetString("Error_EntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error_Error {
            get {
                return ResourceManager.GetString("Error_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei konnte nicht hochgeladen werden..
        /// </summary>
        public static string Error_FileCannotBeUploaded {
            get {
                return ResourceManager.GetString("Error_FileCannotBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Feldeingabe muss zwischen 0 und 100 liegen..
        /// </summary>
        public static string Error_InputRangeMin0Max100 {
            get {
                return ResourceManager.GetString("Error_InputRangeMin0Max100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Feldeingabe muss zwischen 0 und 4 liegen..
        /// </summary>
        public static string Error_InputRangeMin0Max4 {
            get {
                return ResourceManager.GetString("Error_InputRangeMin0Max4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld erfordert eine Eingabe..
        /// </summary>
        public static string Error_InputRequired {
            get {
                return ResourceManager.GetString("Error_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail-Adresse ein..
        /// </summary>
        public static string Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse darf die Länge von 40 Zeichen nicht überschreiten..
        /// </summary>
        public static string Error_InvalidEmailLength {
            get {
                return ResourceManager.GetString("Error_InvalidEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein Passwort mit zwischen 6 und 16 Zeichen ein..
        /// </summary>
        public static string Error_InvalidPassword {
            get {
                return ResourceManager.GetString("Error_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die von Ihnen angegebenen Passwörter stimmen nicht überein..
        /// </summary>
        public static string Error_InvalidPasswordConfirmation {
            get {
                return ResourceManager.GetString("Error_InvalidPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der maximale Wert zur Berechnung der Gewichteten Übereinstimmung ist 0 für ätherisches Öl mit Id {0}. Keine Division durch 0 möglich..
        /// </summary>
        public static string Error_MaxEffectDegreeDiscomfortValueIsZero {
            get {
                return ResourceManager.GetString("Error_MaxEffectDegreeDiscomfortValueIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keine Wirkung für den Suchtext {0} gefunden werden..
        /// </summary>
        public static string Error_NoEffectFoundForSearchText {
            get {
                return ResourceManager.GetString("Error_NoEffectFoundForSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Eintrag mit der Id {0} gelöscht..
        /// </summary>
        public static string Error_NoEntityWithIdDeleted {
            get {
                return ResourceManager.GetString("Error_NoEntityWithIdDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte kein Eintrag mit der Id {0} gefunden werden..
        /// </summary>
        public static string Error_NoEntityWithIdFound {
            get {
                return ResourceManager.GetString("Error_NoEntityWithIdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre angegebenen Daten sind nicht valid..
        /// </summary>
        public static string Error_NotValidData {
            get {
                return ResourceManager.GetString("Error_NotValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebenen Molekülwerte sind nicht valid..
        /// </summary>
        public static string Error_NotValidMoleculePercentage {
            get {
                return ResourceManager.GetString("Error_NotValidMoleculePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte keinen Account mit dieser E-Mail-Adresse gefunden werden..
        /// </summary>
        public static string Error_NoUserWithEmail {
            get {
                return ResourceManager.GetString("Error_NoUserWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es handelt sich dabei nicht um ein gültiges Bildformat..
        /// </summary>
        public static string Error_NoValidPictureFormat {
            get {
                return ResourceManager.GetString("Error_NoValidPictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das alte Passwort ist falsch..
        /// </summary>
        public static string Error_OldPasswordInvalid {
            get {
                return ResourceManager.GetString("Error_OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihr aktuelles Passwort ein..
        /// </summary>
        public static string Error_OldPasswordRequired {
            get {
                return ResourceManager.GetString("Error_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Registration ist fehlgeschlagen..
        /// </summary>
        public static string Error_RegistrationFailed {
            get {
                return ResourceManager.GetString("Error_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ändern Ihres Passwortes ist fehlgeschlagen..
        /// </summary>
        public static string Error_ResetPasswordFailed {
            get {
                return ResourceManager.GetString("Error_ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Suchdaten konnten nicht geladen werden..
        /// </summary>
        public static string Error_SearchDataCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("Error_SearchDataCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Versenden der E-Mail ist fehlgeschlagen..
        /// </summary>
        public static string Error_SendingEmailFailed {
            get {
                return ResourceManager.GetString("Error_SendingEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte versuchen Sie es später noch einmal..
        /// </summary>
        public static string Error_TryAgainLater {
            get {
                return ResourceManager.GetString("Error_TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten..
        /// </summary>
        public static string Error_UnexpectedError {
            get {
                return ResourceManager.GetString("Error_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse wurde bereits registriert..
        /// </summary>
        public static string Error_UserAllreadyRegistered {
            get {
                return ResourceManager.GetString("Error_UserAllreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung zuweisen.
        /// </summary>
        public static string EssentialOil_AssignEffect {
            get {
                return ResourceManager.GetString("EssentialOil_AssignEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl:.
        /// </summary>
        public static string EssentialOil_AssignEffect_EssentialOil {
            get {
                return ResourceManager.GetString("EssentialOil_AssignEffect_EssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molekül zuweisen.
        /// </summary>
        public static string EssentialOil_AssignMolecule {
            get {
                return ResourceManager.GetString("EssentialOil_AssignMolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl:.
        /// </summary>
        public static string EssentialOil_AssignMolecule_EssentialOil {
            get {
                return ResourceManager.GetString("EssentialOil_AssignMolecule_EssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues ätherisches Öl erfassen.
        /// </summary>
        public static string EssentialOil_Create {
            get {
                return ResourceManager.GetString("EssentialOil_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string EssentialOil_Description {
            get {
                return ResourceManager.GetString("EssentialOil_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl bearbeiten.
        /// </summary>
        public static string EssentialOil_Edit {
            get {
                return ResourceManager.GetString("EssentialOil_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirksamkeit.
        /// </summary>
        public static string EssentialOil_EffectDegree {
            get {
                return ResourceManager.GetString("EssentialOil_EffectDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl.
        /// </summary>
        public static string EssentialOil_EssentialOil {
            get {
                return ResourceManager.GetString("EssentialOil_EssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherische Öle.
        /// </summary>
        public static string EssentialOil_EssentialOils {
            get {
                return ResourceManager.GetString("EssentialOil_EssentialOils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EssentialOil_Name {
            get {
                return ResourceManager.GetString("EssentialOil_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateinischer Name.
        /// </summary>
        public static string EssentialOil_NameLatin {
            get {
                return ResourceManager.GetString("EssentialOil_NameLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string EssentialOil_Picture {
            get {
                return ResourceManager.GetString("EssentialOil_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildquelle.
        /// </summary>
        public static string EssentialOil_PictureSource {
            get {
                return ResourceManager.GetString("EssentialOil_PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild entfernen.
        /// </summary>
        public static string EssentialOil_RemovePicture {
            get {
                return ResourceManager.GetString("EssentialOil_RemovePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string EssentialOil_Type {
            get {
                return ResourceManager.GetString("EssentialOil_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fettes Öl.
        /// </summary>
        public static string EssentialOilType_FatOil {
            get {
                return ResourceManager.GetString("EssentialOilType_FatOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrolat.
        /// </summary>
        public static string EssentialOilType_Hydrolat {
            get {
                return ResourceManager.GetString("EssentialOilType_Hydrolat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öl.
        /// </summary>
        public static string EssentialOilType_Oil {
            get {
                return ResourceManager.GetString("EssentialOilType_Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright {0} - Barbara Held - Bern.
        /// </summary>
        public static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duftfinder.
        /// </summary>
        public static string Layout_Duftfinder {
            get {
                return ResourceManager.GetString("Layout_Duftfinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisiert:.
        /// </summary>
        public static string Layout_LastUpdated {
            get {
                return ResourceManager.GetString("Layout_LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abmelden.
        /// </summary>
        public static string Layout_Logoff {
            get {
                return ResourceManager.GetString("Layout_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.barbaraheld.ch/.
        /// </summary>
        public static string Layout_UrlBarbaraHeld {
            get {
                return ResourceManager.GetString("Layout_UrlBarbaraHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Layout_Version {
            get {
                return ResourceManager.GetString("Layout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Molekül erfassen.
        /// </summary>
        public static string Molecule_Create {
            get {
                return ResourceManager.GetString("Molecule_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allgemein.
        /// </summary>
        public static string Molecule_General {
            get {
                return ResourceManager.GetString("Molecule_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molekül.
        /// </summary>
        public static string Molecule_Molecule {
            get {
                return ResourceManager.GetString("Molecule_Molecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moleküle.
        /// </summary>
        public static string Molecule_Molecules {
            get {
                return ResourceManager.GetString("Molecule_Molecules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Molecule_Name {
            get {
                return ResourceManager.GetString("Molecule_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Molecule_Percentage {
            get {
                return ResourceManager.GetString("Molecule_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoffklasse.
        /// </summary>
        public static string Molecule_Substance {
            get {
                return ResourceManager.GetString("Molecule_Substance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Account {0} wurde noch nicht vom Benutzer verifiziert..
        /// </summary>
        public static string Notification_AccountNotVerified_Text {
            get {
                return ResourceManager.GetString("Notification_AccountNotVerified_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account nicht verifizert.
        /// </summary>
        public static string Notification_AccountNotVerified_Title {
            get {
                return ResourceManager.GetString("Notification_AccountNotVerified_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen nicht möglich.
        /// </summary>
        public static string Notification_DeleteNotPossible_Title {
            get {
                return ResourceManager.GetString("Notification_DeleteNotPossible_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag &quot;{0}&quot; kann nicht gelöscht werden. Es handelt sich um den angemeldeten Benutzer..
        /// </summary>
        public static string Notification_DeleteUserNotPossible_Text {
            get {
                return ResourceManager.GetString("Notification_DeleteUserNotPossible_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag &quot;{0}&quot; kann nicht gelöscht werden. Es handelt sich um den Systemadministrator..
        /// </summary>
        public static string Notification_DeleteUserSystemAdminNotPossible_Text {
            get {
                return ResourceManager.GetString("Notification_DeleteUserSystemAdminNotPossible_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobald Sie auf &quot;Speichern&quot; klicken, wird eine E-Mail an {0} gesendet, um den Benutzer über Ihre Bestätigung zu informieren..
        /// </summary>
        public static string Notification_EmailWillBeSentToUser_Text {
            get {
                return ResourceManager.GetString("Notification_EmailWillBeSentToUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs E-Mail an Benutzer senden.
        /// </summary>
        public static string Notification_EmailWillBeSentToUser_Title {
            get {
                return ResourceManager.GetString("Notification_EmailWillBeSentToUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string RoleValue_Admin {
            get {
                return ResourceManager.GetString("RoleValue_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string RoleValue_Friend {
            get {
                return ResourceManager.GetString("RoleValue_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkung.
        /// </summary>
        public static string SearchEffects_Effect {
            get {
                return ResourceManager.GetString("SearchEffects_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschwerdeausmass.
        /// </summary>
        public static string SearchEffects_EffectDegree {
            get {
                return ResourceManager.GetString("SearchEffects_EffectDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anz. Übereinstimmungen.
        /// </summary>
        public static string SearchEffects_MatchAmount {
            get {
                return ResourceManager.GetString("SearchEffects_MatchAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unter dieser Suchanfrage konnten keine ätherischen Öle gefunden werden..
        /// </summary>
        public static string SearchEffects_NoEssentialOilsFound {
            get {
                return ResourceManager.GetString("SearchEffects_NoEssentialOilsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkungen suchen.
        /// </summary>
        public static string SearchEffects_SearchEffects {
            get {
                return ResourceManager.GetString("SearchEffects_SearchEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen Sie nach bis zu fünf Wirkungen, um für Ihre Beschwerden die wirksamsten ätherischen Öle zu finden..
        /// </summary>
        public static string SearchEffects_SearchEffectsDescription {
            get {
                return ResourceManager.GetString("SearchEffects_SearchEffectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von Total:.
        /// </summary>
        public static string SearchEffects_SearchResultAmountText {
            get {
                return ResourceManager.GetString("SearchEffects_SearchResultAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string SearchEffects_SearchResultFilter_10 {
            get {
                return ResourceManager.GetString("SearchEffects_SearchResultFilter_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string SearchEffects_SearchResultFilter_5 {
            get {
                return ResourceManager.GetString("SearchEffects_SearchResultFilter_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string SearchEffects_SearchResultFilter_All {
            get {
                return ResourceManager.GetString("SearchEffects_SearchResultFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl ätherische Öle anzeigen:.
        /// </summary>
        public static string SearchEffects_SearchResultFilterText {
            get {
                return ResourceManager.GetString("SearchEffects_SearchResultFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewichtete Übereinstimmung.
        /// </summary>
        public static string SearchEffects_WeightedMatchValue {
            get {
                return ResourceManager.GetString("SearchEffects_WeightedMatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkungen des ätherischen Öls.
        /// </summary>
        public static string SearchEssentialOil_AssignedEffects {
            get {
                return ResourceManager.GetString("SearchEssentialOil_AssignedEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthaltene Moleküle.
        /// </summary>
        public static string SearchEssentialOil_AssignedMolecules {
            get {
                return ResourceManager.GetString("SearchEssentialOil_AssignedMolecules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string SearchEssentialOil_Description {
            get {
                return ResourceManager.GetString("SearchEssentialOil_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirksamkeit.
        /// </summary>
        public static string SearchEssentialOil_EffectDegree {
            get {
                return ResourceManager.GetString("SearchEssentialOil_EffectDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl.
        /// </summary>
        public static string SearchEssentialOil_EssentialOil {
            get {
                return ResourceManager.GetString("SearchEssentialOil_EssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %-Anteil.
        /// </summary>
        public static string SearchEssentialOil_MoleculePercentage {
            get {
                return ResourceManager.GetString("SearchEssentialOil_MoleculePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateinischer Name.
        /// </summary>
        public static string SearchEssentialOil_NameLatin {
            get {
                return ResourceManager.GetString("SearchEssentialOil_NameLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unter dieser Suchanfrage konnten keine ätherischen Öle gefunden werden..
        /// </summary>
        public static string SearchEssentialOil_NoEssentialOilsFound {
            get {
                return ResourceManager.GetString("SearchEssentialOil_NoEssentialOilsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelle:.
        /// </summary>
        public static string SearchEssentialOil_PictureSource {
            get {
                return ResourceManager.GetString("SearchEssentialOil_PictureSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherisches Öl suchen.
        /// </summary>
        public static string SearchEssentialOil_SearchEssentialOil {
            get {
                return ResourceManager.GetString("SearchEssentialOil_SearchEssentialOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen Sie nach einem ätherischen Öl, um mehr von dessen Zusammensetzung und Wirkungen zu erfahren..
        /// </summary>
        public static string SearchEssentialOil_SearchEssentialOilDescription {
            get {
                return ResourceManager.GetString("SearchEssentialOil_SearchEssentialOilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl gefundene ätherische Öle:.
        /// </summary>
        public static string SearchEssentialOil_SearchResultAmountText {
            get {
                return ResourceManager.GetString("SearchEssentialOil_SearchResultAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string SearchEssentialOil_Type {
            get {
                return ResourceManager.GetString("SearchEssentialOil_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration initialisieren.
        /// </summary>
        public static string Settings_InitializeConfigurationValues {
            get {
                return ResourceManager.GetString("Settings_InitializeConfigurationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirkungen initialisieren.
        /// </summary>
        public static string Settings_InitializeEffects {
            get {
                return ResourceManager.GetString("Settings_InitializeEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ätherische Öle initialisieren.
        /// </summary>
        public static string Settings_InitializeEssentialOils {
            get {
                return ResourceManager.GetString("Settings_InitializeEssentialOils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moleküle initialisieren.
        /// </summary>
        public static string Settings_InitializeMolecules {
            get {
                return ResourceManager.GetString("Settings_InitializeMolecules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoffklassen und Wirkungskategorien initialisieren.
        /// </summary>
        public static string Settings_InitializeSubstancesAndCategories {
            get {
                return ResourceManager.GetString("Settings_InitializeSubstancesAndCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User initialisieren.
        /// </summary>
        public static string Settings_InitializeUsers {
            get {
                return ResourceManager.GetString("Settings_InitializeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Seite dient zur Konfiguration von Duftfinder. Anpassungen können zu Änderungen an der Datenbank führen. Führen Sie die Schritte nur durch, wenn Sie sich über deren Konsequenzen bewusst sind..
        /// </summary>
        public static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldehyde.
        /// </summary>
        public static string SubstanceValue_Aldehyde {
            get {
                return ResourceManager.GetString("SubstanceValue_Aldehyde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aromatische Alkohle.
        /// </summary>
        public static string SubstanceValue_AromaticAlcohol {
            get {
                return ResourceManager.GetString("SubstanceValue_AromaticAlcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aromatische Aldehyde.
        /// </summary>
        public static string SubstanceValue_AromaticAldehyde {
            get {
                return ResourceManager.GetString("SubstanceValue_AromaticAldehyde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aromatische Ester.
        /// </summary>
        public static string SubstanceValue_AromaticEster {
            get {
                return ResourceManager.GetString("SubstanceValue_AromaticEster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumarine.
        /// </summary>
        public static string SubstanceValue_Cumarin {
            get {
                return ResourceManager.GetString("SubstanceValue_Cumarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ester.
        /// </summary>
        public static string SubstanceValue_Ester {
            get {
                return ResourceManager.GetString("SubstanceValue_Ester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketone.
        /// </summary>
        public static string SubstanceValue_Ketone {
            get {
                return ResourceManager.GetString("SubstanceValue_Ketone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoterpene.
        /// </summary>
        public static string SubstanceValue_Monoterpene {
            get {
                return ResourceManager.GetString("SubstanceValue_Monoterpene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoterpenole.
        /// </summary>
        public static string SubstanceValue_Monoterpenole {
            get {
                return ResourceManager.GetString("SubstanceValue_Monoterpenole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxide.
        /// </summary>
        public static string SubstanceValue_Oxide {
            get {
                return ResourceManager.GetString("SubstanceValue_Oxide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenole.
        /// </summary>
        public static string SubstanceValue_Phenole {
            get {
                return ResourceManager.GetString("SubstanceValue_Phenole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phenylpropanderivate.
        /// </summary>
        public static string SubstanceValue_Phenylpropanderivate {
            get {
                return ResourceManager.GetString("SubstanceValue_Phenylpropanderivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesquiterpene.
        /// </summary>
        public static string SubstanceValue_Sesquiterpene {
            get {
                return ResourceManager.GetString("SubstanceValue_Sesquiterpene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesqui- und Diterpenole.
        /// </summary>
        public static string SubstanceValue_SesquiterpenoleDiterpenole {
            get {
                return ResourceManager.GetString("SubstanceValue_SesquiterpenoleDiterpenole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Benutzer erfassen.
        /// </summary>
        public static string UserAdmin_Create {
            get {
                return ResourceManager.GetString("UserAdmin_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bearbeiten.
        /// </summary>
        public static string UserAdmin_Edit {
            get {
                return ResourceManager.GetString("UserAdmin_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string UserAdmin_Email {
            get {
                return ResourceManager.GetString("UserAdmin_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string UserAdmin_FirstName {
            get {
                return ResourceManager.GetString("UserAdmin_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vom Benutzer verifiziert.
        /// </summary>
        public static string UserAdmin_IsAccountVerified {
            get {
                return ResourceManager.GetString("UserAdmin_IsAccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vom Admin bestätigt.
        /// </summary>
        public static string UserAdmin_IsConfirmed {
            get {
                return ResourceManager.GetString("UserAdmin_IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiv.
        /// </summary>
        public static string UserAdmin_IsInactive {
            get {
                return ResourceManager.GetString("UserAdmin_IsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string UserAdmin_LastName {
            get {
                return ResourceManager.GetString("UserAdmin_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string UserAdmin_Password {
            get {
                return ResourceManager.GetString("UserAdmin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        public static string UserAdmin_PasswordConfirmation {
            get {
                return ResourceManager.GetString("UserAdmin_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string UserAdmin_Role {
            get {
                return ResourceManager.GetString("UserAdmin_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string UserAdmin_User {
            get {
                return ResourceManager.GetString("UserAdmin_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerverwaltung.
        /// </summary>
        public static string UserAdmin_UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin_UserAdmin", resourceCulture);
            }
        }
    }
}
